name: saifu_qr
description: A package that enables single to many QR code generation.A single QRcode will simply be shown. Many QRcodes (large QRcode broken into smaller ones), will be displayed and animated from one to other.This package includes addition features that will enable you to change it to suit your criteria.
version: 0.1.0
homepage: https://kiracore.com/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_page_indicator: ^0.0.3
  flutter_swiper: ^1.1.6
  qr_flutter: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
